version: "3"

vars:
  BUILD_TYPE: '{{.BUILD_TYPE | default "Debug"}}'
  BUILD_JOBS: '{{.BUILD_JOBS | default "4"}}'

tasks:
  configure:
    desc: Configure CMake project
    sources:
      - CMakeLists.txt
      - source/**/*.cpp
      - source/**/*.hpp
    generates:
      - build/dev/CMakeCache.txt
    cmds:
      - cmake --preset=dev

  build:
    desc: Build the engine
    deps: [configure]
    sources:
      - source/**/*.cpp
      - source/**/*.hpp
      - example/**/*.cpp
      - example/**/*.hpp
    generates:
      - build/dev/example/sandbox{{exeExt}}
    cmds:
      - cmake --build --preset=dev

  rebuild:
    desc: Clean and rebuild from scratch
    cmds:
      - task: clean
      - task: build

  assets:
    desc: Copy assets to build directory
    sources:
      - example/assets/**/*
      - example/shaders/**/*
      - config.toml
    cmds:
      - mkdir -p build/dev/example/shaders
      - mkdir -p build/dev/example/assets
      - cp -r example/shaders/* build/dev/example/shaders/
      - cp -r example/assets/* build/dev/example/assets/
      - cp config.toml build/dev/example/

  run:
    desc: Run the Sandbox application
    deps: [build, assets]
    dir: build/dev/example
    cmds:
      - ./sandbox{{exeExt}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build

  format:
    desc: Run clang-format on all source files
    cmds:
      - find source example \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \) -print0 | xargs -0 clang-format -i --verbose

  format-check:
    desc: Check if code is formatted correctly (non-destructive)
    cmds:
      - find source example \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \) -print0 | xargs -0 clang-format --dry-run -Werror --verbose

  tidy:
    desc: Run clang-tidy static analysis. Treats warnings as errors.
    deps: [configure]
    cmds:
      - find source example \( -name "*.cpp" -o -name "*.hpp" \) -print0 | xargs -0 clang-tidy -p build/dev

  tidy-fix:
    desc: Run clang-tidy static analysis. Treats warnings as errors.
    deps: [configure]
    cmds:
      - find source example \( -name "*.cpp" -o -name "*.hpp" \) -print0 | xargs -0 clang-tidy -p build/dev -fix

  test:
    desc: Run tests (placeholder for future test infrastructure)
    deps: [build]
    cmds:
      - echo "No tests configured yet"
